const lectures = [
  {
    id: 1,
    title: "المحاضرة الأولى",
    duration: "50 دقيقة",
    description: "تعلم كيفية حساب الإزاحة، السرعة، والتسارع في الحركة الخطية.",
    image: "lecture.svg",
    buttonText: "ابدأ المشاهدة",
  },
  {
    id: 2,
    title: "المحاضرة الثانية",
    duration: "60 دقيقة",
    description: "تعلم كيفية حساب الإزاحة، السرعة، والتسارع في الحركة الخطية.",
    image: "lecture.svg",
    buttonText: "ابدأ المشاهدة",
  },
  {
    id: 3,
    title: "المحاضرة الثالثة",
    duration: "50 دقيقة",
    description: "تعلم كيفية حساب الإزاحة، السرعة، والتسارع في الحركة الخطية.",
    image: "lecture.svg",
    buttonText: "ابدأ المشاهدة",
  },
  {
    id: 4,
    title: "المحاضرة الرابعه",
    duration: "60 دقيقة",
    description: "تعلم كيفية حساب الإزاحة، السرعة، والتسارع في الحركة الخطية.",
    image: "lecture.svg",
    buttonText: "ابدأ المشاهدة",
  },
  {
    id: 5,
    title: "المحاضرة الخامسة",
    duration: "50 دقيقة",
    description: "تعلم كيفية حساب الإزاحة، السرعة، والتسارع في الحركة الخطية.",
    image: "lecture.svg",
    buttonText: "ابدأ المشاهدة",
  },
  {
    id: 6,
    title: "المحاضرة السادسه",
    duration: "60 دقيقة",
    description: "تعلم كيفية حساب الإزاحة، السرعة، والتسارع في الحركة الخطية.",
    image: "lecture.svg",
    buttonText: "ابدأ المشاهدة",
  },
  {
    id: 7,
    title: "المحاضرة السابعه",
    duration: "50 دقيقة",
    description: "تعلم كيفية حساب الإزاحة، السرعة، والتسارع في الحركة الخطية.",
    image: "lecture.svg",
    buttonText: "ابدأ المشاهدة",
  },
  {
    id: 8,
    title: "المحاضرة الثامنه",
    duration: "50 دقيقة",
    description: "تعلم كيفية حساب الإزاحة، السرعة، والتسارع في الحركة الخطية.",
    image: "lecture.svg",
    buttonText: "ابدأ المشاهدة",
  },
  {
    id: 9,
    title: "المحاضرة التاسعه",
    duration: "50 دقيقة",
    description: "تعلم كيفية حساب الإزاحة، السرعة، والتسارع في الحركة الخطية.",
    image: "lecture.svg",
    buttonText: "ابدأ المشاهدة",
  },
];

export default lectures;
