import Header from "../components/Header/Header";
import Main from "../components/Main/Main";

export const metadata = {
  title: "Mr-Omar Roshdy",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <Header />
      <Main />
    </div>
  );
}
